import { test } from 'node:test';
import assert from 'node:assert/strict';
import { initScrollNav } from '../src/scripts/scroll-nav.ts';

test('navigation follows the 20vh boundary, resize, restored scroll, and disposal', () => {
  const win = new EventTarget();
  win.scrollY = 0;
  win.innerHeight = 1000;
  globalThis.window = win;
  globalThis.document = new EventTarget();
  const attributes = new Map();
  const nav = { dataset: {}, inert: false, setAttribute: (key, value) => attributes.set(key, value) };
  initScrollNav(nav);
  assert.equal(nav.inert, true);
  assert.equal(attributes.get('aria-hidden'), 'true');
  win.scrollY = 199; win.dispatchEvent(new Event('scroll'));
  assert.equal(nav.dataset.visible, 'false');
  win.scrollY = 200; win.dispatchEvent(new Event('scroll'));
  assert.equal(nav.dataset.visible, 'true');
  assert.equal(nav.inert, false);
  win.innerHeight = 1100; win.dispatchEvent(new Event('resize'));
  assert.equal(nav.inert, true);
  win.scrollY = 400; win.dispatchEvent(new Event('pageshow'));
  assert.equal(nav.inert, false);
  win.scrollY = 0; win.dispatchEvent(new Event('scroll'));
  assert.equal(nav.inert, true);
  document.dispatchEvent(new Event('astro:before-swap'));
  win.scrollY = 900; win.dispatchEvent(new Event('scroll'));
  assert.equal(nav.inert, true);
});
